/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Dimension;

/**
 *
 * @author davidalejandroruizhernandez
 */
public class AdministradorEmpleados extends javax.swing.JPanel {

    private MenuPrincipal menuPrincipal;
    
    /**
     * Creates new form AdministradorEmpleados
     */
    public AdministradorEmpleados(MenuPrincipal menuPrincipal) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        setPreferredSize(new Dimension(1200, 1000));
        
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        menuPrincipal.mostrarPanel(MenuPrincipal.PanelDestino.MAIN_MENU.getCardName());
        menuPrincipal.setVisible(true);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelDatosAdministracionEmpleados = new javax.swing.JPanel();
        LabelTituloAdministracionEmpleados = new javax.swing.JLabel();
        PanelTablaEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelControlesEmpleados = new javax.swing.JPanel();
        LabelNombreEmpleado = new javax.swing.JLabel();
        LabelDomicilioEmpleado = new javax.swing.JLabel();
        LabelTelefonoEmpleado = new javax.swing.JLabel();
        LabelFechaIngreso = new javax.swing.JLabel();
        LabelNipVentas = new javax.swing.JLabel();
        LabelConfirmaNip = new javax.swing.JLabel();
        LabelTipoEmpleado = new javax.swing.JLabel();
        TextFieldNombreEmpleado = new javax.swing.JTextField();
        TextFieldDomicilioEmpleado = new javax.swing.JTextField();
        TextFieldTelefonoEmpleado = new javax.swing.JTextField();
        TextFieldNip = new javax.swing.JTextField();
        TextFieldConfirmaNip = new javax.swing.JTextField();
        CheckBoxActivoEmpleado = new javax.swing.JCheckBox();
        CheckBoxInactivoEmpleado = new javax.swing.JCheckBox();
        DateChosserEmpleado = new com.toedter.calendar.JDateChooser();
        ComboBoxTipoEmpleado = new javax.swing.JComboBox<>();
        ButtonNuevoEmpleado = new javax.swing.JButton();
        ButtonEditarEmpleado = new javax.swing.JButton();
        ButtonGrabarEmpleado = new javax.swing.JButton();
        ButtonEliminarEmpleado = new javax.swing.JButton();
        ButtonCancelarEmpleados = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        LabelTituloAdministracionEmpleados.setText("jLabel2");

        javax.swing.GroupLayout PanelDatosAdministracionEmpleadosLayout = new javax.swing.GroupLayout(PanelDatosAdministracionEmpleados);
        PanelDatosAdministracionEmpleados.setLayout(PanelDatosAdministracionEmpleadosLayout);
        PanelDatosAdministracionEmpleadosLayout.setHorizontalGroup(
            PanelDatosAdministracionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosAdministracionEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloAdministracionEmpleados)
                .addContainerGap(1148, Short.MAX_VALUE))
        );
        PanelDatosAdministracionEmpleadosLayout.setVerticalGroup(
            PanelDatosAdministracionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosAdministracionEmpleadosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(LabelTituloAdministracionEmpleados)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Domicilio", "Teléfono", "Fecha de Ingreso", "Activo", "Tipo de Empleado", "NIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout PanelTablaEmpleadosLayout = new javax.swing.GroupLayout(PanelTablaEmpleados);
        PanelTablaEmpleados.setLayout(PanelTablaEmpleadosLayout);
        PanelTablaEmpleadosLayout.setHorizontalGroup(
            PanelTablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTablaEmpleadosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelTablaEmpleadosLayout.setVerticalGroup(
            PanelTablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaEmpleadosLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        LabelNombreEmpleado.setText("* Nombre:");

        LabelDomicilioEmpleado.setText("* Domicilio:");

        LabelTelefonoEmpleado.setText("* Telefono:");

        LabelFechaIngreso.setText("* Fecha de Ingreso:");

        LabelNipVentas.setText("* Nip para ventas");

        LabelConfirmaNip.setText("* Confirma Nip para ventas");

        LabelTipoEmpleado.setText("* Tipo de Empleado:");

        CheckBoxActivoEmpleado.setText("Activo");

        CheckBoxInactivoEmpleado.setText("Inactivo");

        ComboBoxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado Mostrador o Vendedor", "Empleado de Cocina", "Repartidor" }));

        ButtonNuevoEmpleado.setText("<html>Nuevo<br>Empleado</html>");

        ButtonEditarEmpleado.setText("Editar Datos");

        ButtonGrabarEmpleado.setText("Grabar");

        ButtonEliminarEmpleado.setText("Eliminar");

        ButtonCancelarEmpleados.setText("Cancelar");

        jButton2.setText("<html>Menu<br>Principal</html>");

        javax.swing.GroupLayout PanelControlesEmpleadosLayout = new javax.swing.GroupLayout(PanelControlesEmpleados);
        PanelControlesEmpleados.setLayout(PanelControlesEmpleadosLayout);
        PanelControlesEmpleadosLayout.setHorizontalGroup(
            PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNipVentas)
                    .addComponent(TextFieldNip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelConfirmaNip)
                    .addComponent(TextFieldConfirmaNip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                                .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNombreEmpleado)
                                    .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextFieldNombreEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelDomicilioEmpleado)
                                        .addComponent(TextFieldDomicilioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(ButtonNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                                .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelFechaIngreso)
                                    .addComponent(DateChosserEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelTelefonoEmpleado)
                                    .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                                        .addComponent(CheckBoxActivoEmpleado)
                                        .addGap(40, 40, 40)
                                        .addComponent(CheckBoxInactivoEmpleado))
                                    .addComponent(LabelTipoEmpleado))
                                .addGap(18, 18, 18)
                                .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonGrabarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonCancelarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelControlesEmpleadosLayout.setVerticalGroup(
            PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(ComboBoxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelNipVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelConfirmaNip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldConfirmaNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                        .addComponent(TextFieldTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelFechaIngreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateChosserEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckBoxActivoEmpleado)
                            .addComponent(CheckBoxInactivoEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTipoEmpleado)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                        .addGroup(PanelControlesEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelControlesEmpleadosLayout.createSequentialGroup()
                                .addComponent(LabelNombreEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelDomicilioEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldDomicilioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTelefonoEmpleado)
                        .addGap(93, 93, 93))
                    .addComponent(ButtonEditarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonGrabarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCancelarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        TextFieldTelefonoEmpleado.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelDatosAdministracionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelTablaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelControlesEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDatosAdministracionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelControlesEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelarEmpleados;
    private javax.swing.JButton ButtonEditarEmpleado;
    private javax.swing.JButton ButtonEliminarEmpleado;
    private javax.swing.JButton ButtonGrabarEmpleado;
    private javax.swing.JButton ButtonNuevoEmpleado;
    private javax.swing.JCheckBox CheckBoxActivoEmpleado;
    private javax.swing.JCheckBox CheckBoxInactivoEmpleado;
    private javax.swing.JComboBox<String> ComboBoxTipoEmpleado;
    private com.toedter.calendar.JDateChooser DateChosserEmpleado;
    private javax.swing.JLabel LabelConfirmaNip;
    private javax.swing.JLabel LabelDomicilioEmpleado;
    private javax.swing.JLabel LabelFechaIngreso;
    private javax.swing.JLabel LabelNipVentas;
    private javax.swing.JLabel LabelNombreEmpleado;
    private javax.swing.JLabel LabelTelefonoEmpleado;
    private javax.swing.JLabel LabelTipoEmpleado;
    private javax.swing.JLabel LabelTituloAdministracionEmpleados;
    private javax.swing.JPanel PanelControlesEmpleados;
    private javax.swing.JPanel PanelDatosAdministracionEmpleados;
    private javax.swing.JPanel PanelTablaEmpleados;
    private javax.swing.JTextField TextFieldConfirmaNip;
    private javax.swing.JTextField TextFieldDomicilioEmpleado;
    private javax.swing.JTextField TextFieldNip;
    private javax.swing.JTextField TextFieldNombreEmpleado;
    private javax.swing.JTextField TextFieldTelefonoEmpleado;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
