/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

//import vista.MenuPrincipal.PanelDestino;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;


/**
 *
 * @author davidalejandroruizhernandez
 */
public class LoginAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form LoginAdministrador
     */
    private MenuPrincipal menuPrincipal;
    
    public LoginAdministrador(MenuPrincipal menuPrincipal) {
        
        initComponents();
        this.menuPrincipal = menuPrincipal;
        setPreferredSize(new Dimension(450, 300));
        menuPrincipal.revalidate();
        menuPrincipal.repaint();
        
        //setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelimagenesLoginAdministrador = new javax.swing.JPanel();
        LabelIntroduceCredenciales = new javax.swing.JLabel();
        PanelBotonesLoginAdministrador = new javax.swing.JPanel();
        LabelUsuarioLoginAdministrador = new javax.swing.JLabel();
        LabelPassLoginAdministrador = new javax.swing.JLabel();
        PassFieldLoginAdministrador = new javax.swing.JPasswordField();
        TextFieldUsuarioLoginAdministrador = new javax.swing.JTextField();
        ButtonAceptarLoginAdministrador = new javax.swing.JButton();
        ButtonCancelarLoginAdministrador = new javax.swing.JButton();

        PanelimagenesLoginAdministrador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelIntroduceCredenciales.setText("Introduce tus credenciales");
        LabelIntroduceCredenciales.setToolTipText("");

        javax.swing.GroupLayout PanelimagenesLoginAdministradorLayout = new javax.swing.GroupLayout(PanelimagenesLoginAdministrador);
        PanelimagenesLoginAdministrador.setLayout(PanelimagenesLoginAdministradorLayout);
        PanelimagenesLoginAdministradorLayout.setHorizontalGroup(
            PanelimagenesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelimagenesLoginAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelIntroduceCredenciales)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        PanelimagenesLoginAdministradorLayout.setVerticalGroup(
            PanelimagenesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelimagenesLoginAdministradorLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(LabelIntroduceCredenciales)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        LabelUsuarioLoginAdministrador.setText("* Usuario:");
        LabelUsuarioLoginAdministrador.setToolTipText("");

        LabelPassLoginAdministrador.setText("*Contraseña:");
        LabelPassLoginAdministrador.setToolTipText("");

        TextFieldUsuarioLoginAdministrador.setToolTipText("");

        ButtonAceptarLoginAdministrador.setText("Aceptar");
        ButtonAceptarLoginAdministrador.setToolTipText("");
        ButtonAceptarLoginAdministrador.addActionListener(this::ButtonAceptarLoginAdministradorActionPerformed);

        ButtonCancelarLoginAdministrador.setText("Cancelar");
        ButtonCancelarLoginAdministrador.setToolTipText("");
        ButtonCancelarLoginAdministrador.addActionListener(this::ButtonCancelarLoginAdministradorActionPerformed);

        javax.swing.GroupLayout PanelBotonesLoginAdministradorLayout = new javax.swing.GroupLayout(PanelBotonesLoginAdministrador);
        PanelBotonesLoginAdministrador.setLayout(PanelBotonesLoginAdministradorLayout);
        PanelBotonesLoginAdministradorLayout.setHorizontalGroup(
            PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLoginAdministradorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuarioLoginAdministrador)
                    .addComponent(LabelPassLoginAdministrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesLoginAdministradorLayout.createSequentialGroup()
                        .addComponent(PassFieldLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonAceptarLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCancelarLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldUsuarioLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PanelBotonesLoginAdministradorLayout.setVerticalGroup(
            PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLoginAdministradorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUsuarioLoginAdministrador)
                    .addComponent(TextFieldUsuarioLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPassLoginAdministrador)
                    .addComponent(PassFieldLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonesLoginAdministradorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelBotonesLoginAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAceptarLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCancelarLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBotonesLoginAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelimagenesLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelimagenesLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBotonesLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAceptarLoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarLoginAdministradorActionPerformed
        // TODO add your handling code here:
        menuPrincipal.mostrarPanel(MenuPrincipal.PanelDestino.ADMIN_EMPLEADOS.getCardName());
    }//GEN-LAST:event_ButtonAceptarLoginAdministradorActionPerformed

    private void ButtonCancelarLoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarLoginAdministradorActionPerformed
        // TODO add your handling code here:
        menuPrincipal.mostrarPanel(MenuPrincipal.PanelDestino.MAIN_MENU.getCardName());
    }//GEN-LAST:event_ButtonCancelarLoginAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceptarLoginAdministrador;
    private javax.swing.JButton ButtonCancelarLoginAdministrador;
    private javax.swing.JLabel LabelIntroduceCredenciales;
    private javax.swing.JLabel LabelPassLoginAdministrador;
    private javax.swing.JLabel LabelUsuarioLoginAdministrador;
    private javax.swing.JPanel PanelBotonesLoginAdministrador;
    private javax.swing.JPanel PanelimagenesLoginAdministrador;
    private javax.swing.JPasswordField PassFieldLoginAdministrador;
    private javax.swing.JTextField TextFieldUsuarioLoginAdministrador;
    // End of variables declaration//GEN-END:variables
}
