/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author davidalejandroruizhernandez
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    private CardLayout cardLayout;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        
       
       //FlatLightLaf.setup();
       FlatDarkLaf.setup();
       SwingUtilities.invokeLater(() -> {
            initComponents();
            cardLayout = new CardLayout();
            PanelPrincipal.setLayout(cardLayout);
            PanelPrincipal.add(new MainMenu(),"MENU");
            PanelPrincipal.add(new AdministradorEmpleados(), "EMPLEADOS");
            PanelPrincipal.add(new LoginAdministrador(this),"LOGIN_ADMINISTRADOR");
            PanelPrincipal.add(new LoginGerente(this), "LOGIN_GERENTE");
            cardLayout.show(PanelPrincipal,"MENU");    
            this.setLocationRelativeTo(null);
            pack();
            //Faltan agregar mas como
            // Aquí creas y muestras tu ventana (JFrame)
            //cardLayout = new CardLayout();
            //PanelPrincipal.setLayout(cardLayout);
            //PanelPrincipal.add(new MenuPrincipal(), "Menu");
            //PanelPrincipal.add(new LoginAdministrador(this), "Login Administrador");
            //PanelPrincipal.add(new LoginGerente(this), "Login Gerente");
            //mostrarPanel("Menu");
       
        });
       
        
    }
    
    public void mostrarPanel(String nombre) {
        cardLayout.show(PanelPrincipal, nombre);
    }
    
    public enum PanelDestino{
        EMPLEADOS,
        REIMPRESION,
        CANCELACIONES,
        CORTE_PARCIAL,
        CORTE_TOTAL,
        ADMINISTRACION_SUCURSAL
    }
    
    private void inicializarPaneles(){
        cardLayout = new CardLayout();
        PanelPrincipal.setLayout(cardLayout);
        PanelPrincipal.add(new LoginAdministrador(this), "Login Administrador");
        PanelPrincipal.add(new LoginGerente(this), "Login Gerente");
        
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
