/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.mycompany.administradorpizzeriav2.DBConfiguration;
import java.awt.Dimension;
import java.io.IOException;
import java.lang.module.Configuration;
import javax.swing.JOptionPane;

/**
 *
 * @author davidalejandroruizhernandez
 */
public class PanelConexionBD extends javax.swing.JPanel {

    /**
     * Creates new form PanelConexionBD
     */
    public PanelConexionBD(MenuPrincipal menuPrincipal) {
        
        
        initComponents();
        setPreferredSize(new Dimension(630, 545));
        //this.setResizable(false);
        menuPrincipal.revalidate();
        menuPrincipal.repaint();
        
        // Mostrar la configuracion guardada dentro del archivo config.properties
        LabelIpConfiguredBD.setText(DBConfiguration.getHost());
        LabelBDNameConfiguredBD.setText(DBConfiguration.getBaseDatos());
        LabelUserConfiguredBD.setText(DBConfiguration.getUsuario());
        LabelPassConfiguredBD.setText(DBConfiguration.getPassword());
        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelDatosBD = new javax.swing.JPanel();
        LabelTituloBD = new javax.swing.JLabel();
        LabelSubTituloConfigBD = new javax.swing.JLabel();
        LabelIpParameterBD = new javax.swing.JLabel();
        LabelBDparameterBD = new javax.swing.JLabel();
        LabelUsuarioParameterBD = new javax.swing.JLabel();
        LabelPassParameterBD = new javax.swing.JLabel();
        LabelIpConfiguredBD = new javax.swing.JLabel();
        LabelBDNameConfiguredBD = new javax.swing.JLabel();
        LabelUserConfiguredBD = new javax.swing.JLabel();
        LabelPassConfiguredBD = new javax.swing.JLabel();
        LabelPuertoParameterBD = new javax.swing.JLabel();
        LabelPuertoConfiguredBD = new javax.swing.JLabel();
        LabelIconBD = new javax.swing.JLabel();
        PanelCamposBD = new javax.swing.JPanel();
        LabelTitleNuevaConexionBD = new javax.swing.JLabel();
        LabelHostTitleBD = new javax.swing.JLabel();
        LabelTitleBD = new javax.swing.JLabel();
        LabelUsuarioBD = new javax.swing.JLabel();
        LabelPassBD = new javax.swing.JLabel();
        ButtonProbarConexionBD = new javax.swing.JButton();
        TextFieldHostBD = new javax.swing.JTextField();
        TextFieldBD = new javax.swing.JTextField();
        TextFieldUsuarioBD = new javax.swing.JTextField();
        ButtonCancelarBD = new javax.swing.JButton();
        ButtonActualizarBD = new javax.swing.JButton();
        PassFieldDB = new javax.swing.JPasswordField();
        LabelPuertoBD = new javax.swing.JLabel();
        TextFieldPuertoBD = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(630, 590));

        PanelDatosBD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelTituloBD.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelTituloBD.setText("* Configuración a la Base de Datos");

        LabelSubTituloConfigBD.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelSubTituloConfigBD.setText("* Configuración Actual");

        LabelIpParameterBD.setText("* Host:");
        LabelIpParameterBD.setToolTipText("");

        LabelBDparameterBD.setText("* Base de Datos:");

        LabelUsuarioParameterBD.setText("* Usuario:");

        LabelPassParameterBD.setText("* Contraseña:");

        LabelIpConfiguredBD.setText("??");

        LabelBDNameConfiguredBD.setText("??");

        LabelUserConfiguredBD.setText("??");

        LabelPassConfiguredBD.setText("??");

        LabelPuertoParameterBD.setText("* Puerto:");

        LabelPuertoConfiguredBD.setText("??");

        LabelIconBD.setText("jLabel1");

        javax.swing.GroupLayout PanelDatosBDLayout = new javax.swing.GroupLayout(PanelDatosBD);
        PanelDatosBD.setLayout(PanelDatosBDLayout);
        PanelDatosBDLayout.setHorizontalGroup(
            PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosBDLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosBDLayout.createSequentialGroup()
                        .addComponent(LabelIpParameterBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelIpConfiguredBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelIconBD)
                        .addGap(138, 138, 138))
                    .addGroup(PanelDatosBDLayout.createSequentialGroup()
                        .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTituloBD)
                            .addComponent(LabelSubTituloConfigBD))
                        .addContainerGap(297, Short.MAX_VALUE))
                    .addGroup(PanelDatosBDLayout.createSequentialGroup()
                        .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosBDLayout.createSequentialGroup()
                                .addComponent(LabelPuertoParameterBD)
                                .addGap(2, 2, 2)
                                .addComponent(LabelPuertoConfiguredBD))
                            .addGroup(PanelDatosBDLayout.createSequentialGroup()
                                .addComponent(LabelPassParameterBD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelPassConfiguredBD))
                            .addGroup(PanelDatosBDLayout.createSequentialGroup()
                                .addComponent(LabelUsuarioParameterBD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelUserConfiguredBD))
                            .addGroup(PanelDatosBDLayout.createSequentialGroup()
                                .addComponent(LabelBDparameterBD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelBDNameConfiguredBD)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelDatosBDLayout.setVerticalGroup(
            PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosBDLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelTituloBD)
                .addGap(28, 28, 28)
                .addComponent(LabelSubTituloConfigBD)
                .addGap(14, 14, 14)
                .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIconBD)
                    .addComponent(LabelIpParameterBD)
                    .addComponent(LabelIpConfiguredBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPuertoParameterBD)
                    .addComponent(LabelPuertoConfiguredBD))
                .addGap(12, 12, 12)
                .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBDparameterBD)
                    .addComponent(LabelBDNameConfiguredBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUsuarioParameterBD)
                    .addComponent(LabelUserConfiguredBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPassParameterBD)
                    .addComponent(LabelPassConfiguredBD))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        LabelTitleNuevaConexionBD.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelTitleNuevaConexionBD.setText("Nueva Conexión a la Base de Datos");
        LabelTitleNuevaConexionBD.setToolTipText("");

        LabelHostTitleBD.setText("* Host:");

        LabelTitleBD.setText("* Base de Datos:");

        LabelUsuarioBD.setText("* Usuario:");

        LabelPassBD.setText("* Contraseña:");

        ButtonProbarConexionBD.setText("Probar Conexión");

        ButtonCancelarBD.setText("Cancelar");

        ButtonActualizarBD.setText("Actualizar");
        ButtonActualizarBD.addActionListener(this::ButtonActualizarBDActionPerformed);

        LabelPuertoBD.setText("* Puerto");

        javax.swing.GroupLayout PanelCamposBDLayout = new javax.swing.GroupLayout(PanelCamposBD);
        PanelCamposBD.setLayout(PanelCamposBDLayout);
        PanelCamposBDLayout.setHorizontalGroup(
            PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCamposBDLayout.createSequentialGroup()
                .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCamposBDLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCamposBDLayout.createSequentialGroup()
                                .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelHostTitleBD)
                                    .addComponent(LabelUsuarioBD)
                                    .addComponent(LabelPassBD)
                                    .addComponent(LabelTitleBD)
                                    .addComponent(LabelPuertoBD))
                                .addGap(18, 18, 18)
                                .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldBD, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(TextFieldHostBD, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(TextFieldUsuarioBD, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(PassFieldDB)
                                    .addComponent(TextFieldPuertoBD)))
                            .addComponent(LabelTitleNuevaConexionBD)))
                    .addGroup(PanelCamposBDLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(ButtonProbarConexionBD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonActualizarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCancelarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        PanelCamposBDLayout.setVerticalGroup(
            PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCamposBDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCamposBDLayout.createSequentialGroup()
                        .addComponent(LabelTitleNuevaConexionBD)
                        .addGap(18, 18, 18)
                        .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelHostTitleBD)
                            .addComponent(TextFieldHostBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPuertoBD)
                            .addComponent(TextFieldPuertoBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addComponent(ButtonActualizarBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCamposBDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTitleBD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldUsuarioBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelUsuarioBD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCamposBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PassFieldDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelPassBD))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonProbarConexionBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCamposBDLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ButtonCancelarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelDatosBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelCamposBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelDatosBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCamposBD, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActualizarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarBDActionPerformed
        // TODO add your handling code here:
        
        //Validaciones antes de guardar las configuraciones de la BD
        if(TextFieldHostBD.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El host es obligatorio.");
            return;
        }
        
        if(TextFieldPuertoBD.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El host es obligatorio.");
            return;
        }else{
            try {
                    Integer.parseInt(TextFieldPuertoBD.getText().trim());
                 } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "El puerto debe ser un número.");
                        return;
                }
        }
        
        if(TextFieldUsuarioBD.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El host es obligatorio.");
            return;
        }
        
        if(PassFieldDB.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El host es obligatorio.");
            return;
        }
        
        
        try{
            DBConfiguration.actualizarConfiguracion(TextFieldHostBD.getText().trim(),
                    TextFieldPuertoBD.getText().trim(), 
                    TextFieldBD.getText().trim(), 
                    TextFieldUsuarioBD.getText().trim(),
                    new String(PassFieldDB.getPassword())
            );
            
            JOptionPane.showMessageDialog(this, "Configuracion guardada correctamente");
            
        } catch (Exception ex){
                JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
               );
        }
        
        
    }//GEN-LAST:event_ButtonActualizarBDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizarBD;
    private javax.swing.JButton ButtonCancelarBD;
    private javax.swing.JButton ButtonProbarConexionBD;
    private javax.swing.JLabel LabelBDNameConfiguredBD;
    private javax.swing.JLabel LabelBDparameterBD;
    private javax.swing.JLabel LabelHostTitleBD;
    private javax.swing.JLabel LabelIconBD;
    private javax.swing.JLabel LabelIpConfiguredBD;
    private javax.swing.JLabel LabelIpParameterBD;
    private javax.swing.JLabel LabelPassBD;
    private javax.swing.JLabel LabelPassConfiguredBD;
    private javax.swing.JLabel LabelPassParameterBD;
    private javax.swing.JLabel LabelPuertoBD;
    private javax.swing.JLabel LabelPuertoConfiguredBD;
    private javax.swing.JLabel LabelPuertoParameterBD;
    private javax.swing.JLabel LabelSubTituloConfigBD;
    private javax.swing.JLabel LabelTitleBD;
    private javax.swing.JLabel LabelTitleNuevaConexionBD;
    private javax.swing.JLabel LabelTituloBD;
    private javax.swing.JLabel LabelUserConfiguredBD;
    private javax.swing.JLabel LabelUsuarioBD;
    private javax.swing.JLabel LabelUsuarioParameterBD;
    private javax.swing.JPanel PanelCamposBD;
    private javax.swing.JPanel PanelDatosBD;
    private javax.swing.JPasswordField PassFieldDB;
    private javax.swing.JTextField TextFieldBD;
    private javax.swing.JTextField TextFieldHostBD;
    private javax.swing.JTextField TextFieldPuertoBD;
    private javax.swing.JTextField TextFieldUsuarioBD;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
